{
 "title": "FoundationDB",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=~\"MUSIC_FDB_.*\"}, cluster)"
    }
   },
   { "name": "interval", "query": "1m,2m,5m,10m" },
   {
    "name": "machine",
    "query": {
     "query": "label_values(fdb_machine_workers{job=~\"MUSIC_FDB_.*\", cluster=\"$cluster\"}, address)"
    }
   },
   {
    "name": "storage_process",
    "query": {
     "query": "label_values(fdb_process_storage_data_lag_seconds{job=~\"MUSIC_FDB_.*\", cluster=\"$cluster\", role=\"storage\"}, address)"
    }
   },
   {
    "name": "log_process",
    "query": {
     "query": "label_values(fdb_process_log_queue_disk_available_bytes{job=~\"MUSIC_FDB_.*\", cluster=\"$cluster\", role=\"log\"}, address)"
    }
   },
   {
    "name": "commit_proxy_process",
    "query": {
     "query": "label_values(fdb_process_commit_proxy_batching_window_size_mean{job=~\"MUSIC_FDB_.*\", cluster=\"$cluster\", role=\"commit_proxy\"}, address)"
    }
   },
   {
    "name": "grv_proxy_process",
    "query": {
     "query": "label_values(fdb_process_grv_proxy_batch_latency_mean{job=~\"MUSIC_FDB_.*\", cluster=\"$cluster\", role=\"grv_proxy\"}, address)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database is Available",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "fdb_cluster_database_available{cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Database is Locked",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "fdb_cluster_database_locked{cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Clients",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "fdb_cluster_clients_count{cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Exporter Latency",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "fdb_exporter_latency_ms{cluster=\"$cluster\"}",
       "legendFormat": "Latency"
      }
     ]
    },
    {
     "title": "Redundancy Mode",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "fdb_cluster_config_redundancy_mode{cluster=\"$cluster\"}",
       "legendFormat": "{{mode}}"
      }
     ]
    },
    {
     "title": "Coordinators",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "fdb_client_coordinators{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Processes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "fdb_cluster_process{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Machines",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "fdb_cluster_machine{cluster=\"$cluster\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Workload",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Operations",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(fdb_cluster_workload_operations_read_requests{cluster=\"$cluster\"}[$interval])",
       "legendFormat": "Read Requests"
      },
      {
       "expr": "rate(fdb_cluster_workload_operations_reads{cluster=\"$cluster\"}[$interval])",
       "legendFormat": "Reads"
      },
      {
       "expr": "rate(fdb_cluster_workload_operations_writes{cluster=\"$cluster\"}[$interval])",
       "legendFormat": "Writes"
      }
     ]
    },
    {
     "title": "Transactions",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(fdb_cluster_workload_transactions_started{cluster=\"$cluster\"}[$interval])",
       "legendFormat": "Started"
      },
      {
       "expr": "rate(fdb_cluster_workload_transactions_committed{cluster=\"$cluster\"}[$interval])",
       "legendFormat": "Committed"
      }
     ]
    },
    {
     "title": "Transaction Conflicts",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 5, "x": 10, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(fdb_cluster_workload_transactions_conflicted{cluster=\"$cluster\"}[$interval])",
       "legendFormat": "Conflicted"
      }
     ]
    },
    {
     "title": "Keys Read",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 5, "x": 15, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(fdb_cluster_workload_keys_read{cluster=\"$cluster\"}[$interval])",
       "legendFormat": "Keys Read"
      }
     ]
    },
    {
     "title": "Data",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(fdb_cluster_workload_bytes_read{cluster=\"$cluster\"}[$interval])",
       "legendFormat": "Bytes Read"
      },
      {
       "expr": "rate(fdb_cluster_workload_bytes_written{cluster=\"$cluster\"}[$interval])",
       "legendFormat": "Bytes Written"
      }
     ]
    }
   ]
  },
  {
   "title": "QoS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Performance Limited By",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "fdb_cluster_qos_performance_limited_by{cluster=\"$cluster\"}",
       "legendFormat": "{{description}}"
      }
     ]
    },
    {
     "title": "Transactions per Second Limit",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "fdb_cluster_qos_transactions_per_second_limit{cluster=\"$cluster\"}",
       "legendFormat": "Transactions per second limit"
      },
      {
       "expr": "fdb_cluster_qos_batch_transactions_per_second_limit{cluster=\"$cluster\"}",
       "legendFormat": "Batch transactions per second limit"
      }
     ]
    },
    {
     "title": "Released Transactions per Second",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "fdb_cluster_qos_released_transactions_per_second{cluster=\"$cluster\"}",
       "legendFormat": "Released transactions per second"
      },
      {
       "expr": "fdb_cluster_qos_batch_released_transactions_per_second{cluster=\"$cluster\"}",
       "legendFormat": "Batch released transactions per second"
      }
     ]
    },
    {
     "title": "Batch Performance Limited By",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "fdb_cluster_qos_batch_performance_limited_by{cluster=\"$cluster\"}",
       "legendFormat": "{{description}}"
      }
     ]
    },
    {
     "title": "Storage Server Durability Lag",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "fdb_cluster_qos_limiting_storage_server_durability_lag_seconds{cluster=\"$cluster\"}",
       "legendFormat": "Limiting"
      },
      {
       "expr": "fdb_cluster_qos_worst_storage_server_durability_lag_seconds{cluster=\"$cluster\"}",
       "legendFormat": "Worst"
      }
     ]
    },
    {
     "title": "Storage Server Data Lag",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "fdb_cluster_qos_limiting_storage_server_data_lag_seconds{cluster=\"$cluster\"}",
       "legendFormat": "Limiting"
      },
      {
       "expr": "fdb_cluster_qos_worst_storage_server_data_lag_seconds{cluster=\"$cluster\"}",
       "legendFormat": "Worst"
      }
     ]
    },
    {
     "title": "Storage Server Queue",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "fdb_cluster_qos_limiting_storage_server_queue_bytes{cluster=\"$cluster\"}",
       "legendFormat": "Limiting"
      },
      {
       "expr": "fdb_cluster_qos_worst_storage_server_queue_bytes{cluster=\"$cluster\"}",
       "legendFormat": "Worst"
      }
     ]
    },
    {
     "title": "Log Server Queue",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "fdb_cluster_qos_worst_log_server_queue_bytes{cluster=\"$cluster\"}",
       "legendFormat": "Worst"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency Probe",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "fdb_cluster_latency_probe_read_seconds{cluster=\"$cluster\"}",
       "legendFormat": "Time to perform a single read"
      }
     ]
    },
    {
     "title": "Commit",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "fdb_cluster_latency_probe_commit_seconds{cluster=\"$cluster\"}",
       "legendFormat": "Time to commit a sample transaction"
      }
     ]
    },
    {
     "title": "Transaction Start",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "fdb_cluster_latency_probe_transaction_start_seconds{cluster=\"$cluster\"}",
       "legendFormat": "Time to start a sample transaction at normal priority"
      },
      {
       "expr": "fdb_cluster_latency_probe_immediate_priority_transaction_start_seconds{cluster=\"$cluster\"}",
       "legendFormat": "Time to start a sample transaction at system immediate priority"
      },
      {
       "expr": "fdb_cluster_latency_probe_batch_priority_transaction_start_seconds{cluster=\"$cluster\"}",
       "legendFormat": "Time to start a sample transaction at batch priority"
      }
     ]
    }
   ]
  },
  {
   "title": "Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "State",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "fdb_cluster_data_state{cluster=\"$cluster\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Total disk used",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "fdb_cluster_data_total_disk_used_bytes{cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Total KV size",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "fdb_cluster_data_total_kv_size_bytes{cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Operating space on most full storage server",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "fdb_cluster_data_least_operating_space_storage_server_bytes{cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Operating space on most full log server",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "fdb_cluster_data_least_operating_space_log_server_bytes{cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Moving data in-queue bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "fdb_cluster_data_moving_in_queue_bytes{cluster=\"$cluster\"}",
       "legendFormat": "In-queue bytes"
      }
     ]
    },
    {
     "title": "Moving data in-flight bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "fdb_cluster_data_moving_in_flight_byte{cluster=\"$cluster\"}",
       "legendFormat": "In-flight bytes"
      }
     ]
    },
    {
     "title": "Moving data rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(fdb_cluster_data_moving_total_written_bytes{cluster=\"$cluster\"}[$interval])",
       "legendFormat": "Moving data rate"
      }
     ]
    },
    {
     "title": "System KV size",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "fdb_cluster_data_system_kv_size_bytes{cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Average partition size",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "fdb_cluster_data_average_partition_size_bytes{cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Partitions",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "fdb_cluster_data_partitions{cluster=\"$cluster\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Recovery State",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Recovery State",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "fdb_cluster_recovery_state{cluster=\"$cluster\"}",
       "legendFormat": "{{description}}"
      }
     ]
    },
    {
     "title": "Active Generations",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "fdb_cluster_recovery_state_active_generations{cluster=\"$cluster\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Machine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workers $machine",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "fdb_machine_workers{cluster=\"$cluster\", address=\"$machine\"}",
       "legendFormat": "workers"
      }
     ]
    },
    {
     "title": "CPU $machine",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "fdb_machine_logical_core_utils{cluster=\"$cluster\", address=\"$machine\"}",
       "legendFormat": "utils"
      }
     ]
    },
    {
     "title": "Memory  $machine",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fdb_machine_memory_total_bytes{cluster=\"$cluster\", address=\"$machine\"}",
       "legendFormat": "total"
      },
      {
       "expr": "fdb_machine_memory_free_bytes{cluster=\"$cluster\", address=\"$machine\"}",
       "legendFormat": "free"
      },
      {
       "expr": "fdb_machine_memory_committed_bytes{cluster=\"$cluster\", address=\"$machine\"}",
       "legendFormat": "committed"
      }
     ]
    },
    {
     "title": "Network $machine",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "expr": "fdb_machine_network_megabits_received_rate{cluster=\"$cluster\", address=\"$machine\"}",
       "legendFormat": "received"
      },
      {
       "expr": "fdb_machine_network_megabits_sent_rate{cluster=\"$cluster\", address=\"$machine\"}",
       "legendFormat": "sent"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
     "repeat": "storage_processes",
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(fdb_process_storage_input_bytes{cluster=\"$cluster\", address=\"$storage_process\", role=\"storage\"}[$interval])",
       "legendFormat": "input $storage_process"
      },
      {
       "expr": "rate(fdb_process_storage_durable_bytes{cluster=\"$cluster\", address=\"$storage_process\", role=\"storage\"}[$interval])",
       "legendFormat": "durable $storage_process"
      },
      {
       "expr": "max(rate(fdb_process_storage_input_bytes{cluster=\"$cluster\", role=\"storage\"}[$interval]))",
       "legendFormat": "input max"
      },
      {
       "expr": "max(rate(fdb_process_storage_durable_bytes{cluster=\"$cluster\", role=\"storage\"}[$interval]))",
       "legendFormat": "durable max"
      }
     ]
    },
    {
     "title": "Lag",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
     "repeat": "storage_processes",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "fdb_process_storage_data_lag_seconds{cluster=\"$cluster\", role=\"storage\", address=\"$storage_process\"}",
       "legendFormat": "data {{address}}"
      },
      {
       "expr": "fdb_process_storage_durability_lag_seconds{cluster=\"$cluster\", role=\"storage\", address=\"$storage_process\"}",
       "legendFormat": "durability {{address}}"
      },
      {
       "expr": "max(fdb_process_storage_data_lag_seconds{cluster=\"$cluster\", role=\"storage\"})",
       "legendFormat": "data max"
      },
      {
       "expr": "max(fdb_process_storage_durability_lag_seconds{cluster=\"$cluster\", role=\"storage\"})",
       "legendFormat": "durability  max"
      }
     ]
    },
    {
     "title": "Read Latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
     "repeat": "storage_processes",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "fdb_process_storage_read_latency_mean{cluster=\"$cluster\", role=\"storage\", address=\"$storage_process\"}",
       "legendFormat": "mean {{address}}"
      },
      {
       "expr": "fdb_process_storage_read_latency_p99{cluster=\"$cluster\", role=\"storage\", address=\"$storage_process\"}",
       "legendFormat": "p99 {{address}}"
      },
      {
       "expr": "fdb_process_storage_read_latency_max{cluster=\"$cluster\", role=\"storage\", address=\"$storage_process\"}",
       "legendFormat": "max {{address}}"
      },
      {
       "expr": "max(fdb_process_storage_read_latency_max{cluster=\"$cluster\", role=\"storage\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 22 },
     "repeat": "storage_processes",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(fdb_process_cpu_usage_cores{cluster=\"$cluster\",class_type=~\"(storage|unset)\"})",
       "legendFormat": "core max"
      },
      {
       "expr": "fdb_process_cpu_usage_cores{cluster=\"$cluster\",address=\"$storage_process\"}",
       "legendFormat": "cores {{address}} {{class_type}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fdb_process_memory_available_bytes{cluster=\"$cluster\", address=\"$storage_process\"}",
       "legendFormat": "available {{address}}"
      },
      {
       "expr": "fdb_process_memory_used_bytes{cluster=\"$cluster\", address=\"$storage_process\"}",
       "legendFormat": "used {{address}}"
      },
      {
       "expr": "fdb_process_memory_rss_bytes{cluster=\"$cluster\", address=\"$storage_process\"}",
       "legendFormat": "rss {{address}}"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 22 },
     "repeat": "storage_processes",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "fdb_process_disk_usage_ratio{cluster=\"$cluster\", address=\"$storage_process\"}",
       "legendFormat": "usage {{address}}"
      },
      {
       "expr": "max(fdb_process_disk_usage_ratio{cluster=\"$cluster\", class_type=~\"(storage|unset)\"})",
       "legendFormat": "usage max"
      }
     ]
    },
    {
     "title": "Network",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 22 },
     "repeat": "storage_processes",
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "fdb_process_network_megabits_received_rate{cluster=\"$cluster\", address=\"$storage_process\"}",
       "legendFormat": "received {{address}}"
      },
      {
       "expr": "fdb_process_network_megabits_sent_rate{cluster=\"$cluster\", address=\"$storage_process\"}",
       "legendFormat": "sent {{address}}"
      },
      {
       "expr": "max(fdb_process_network_megabits_received_rate{cluster=\"$cluster\", class_type=~\"(storage|unset)\"})",
       "legendFormat": "received max"
      },
      {
       "expr": "max(fdb_process_network_megabits_sent_rate{cluster=\"$cluster\", class_type=~\"(storage|unset)\"})",
       "legendFormat": "sent max"
      }
     ]
    }
   ]
  },
  {
   "title": "Log Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "repeat": "log_processes",
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(fdb_process_log_input_bytes{cluster=\"$cluster\", address=\"$log_process\"}[$interval])",
       "legendFormat": "input {{address}}"
      },
      {
       "expr": "rate(fdb_process_log_durable_bytes{cluster=\"$cluster\", address=\"$log_process\"}[$interval])",
       "legendFormat": "durable {{address}}"
      },
      {
       "expr": "max(rate(fdb_process_log_input_bytes{cluster=\"$cluster\", role=\"log\"}[$interval]))",
       "legendFormat": "input max"
      },
      {
       "expr": "max(rate(fdb_process_log_durable_bytes{cluster=\"$cluster\", role=\"log\"}[$interval]))",
       "legendFormat": "durable max"
      }
     ]
    },
    {
     "title": "Data Queue Disk",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "fdb_process_log_queue_disk_available_bytes{cluster=\"$cluster\", address=\"$log_process\"}",
       "legendFormat": "avail {{address}}"
      },
      {
       "expr": "fdb_process_log_queue_disk_total_bytes{cluster=\"$cluster\", address=\"$log_process\"}",
       "legendFormat": "total {{address}}"
      },
      {
       "expr": "fdb_process_log_queue_disk_used_bytes{cluster=\"$cluster\", address=\"$log_process\"}",
       "legendFormat": "used {{address}}"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
     "repeat": "log_processes",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "fdb_process_cpu_usage_cores{cluster=\"$cluster\",address=\"$log_process\"}",
       "legendFormat": "core {{address}} {{class_type}}"
      },
      {
       "expr": "max(fdb_process_cpu_usage_cores{cluster=\"$cluster\",class_type=~\"(log|unset)\"})",
       "legendFormat": "core max"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fdb_process_memory_available_bytes{cluster=\"$cluster\", address=\"$log_process\"}",
       "legendFormat": "available {{address}}"
      },
      {
       "expr": "fdb_process_memory_used_bytes{cluster=\"$cluster\", address=\"$log_process\"}",
       "legendFormat": "used {{address}}"
      },
      {
       "expr": "fdb_process_memory_rss_bytes{cluster=\"$cluster\", address=\"$log_process\"}",
       "legendFormat": "rss {{address}}"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 16 },
     "repeat": "log_processes",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "fdb_process_disk_usage_ratio{cluster=\"$cluster\", address=\"$log_process\"}",
       "legendFormat": "usage {{address}}"
      },
      {
       "expr": "max(fdb_process_disk_usage_ratio{cluster=\"$cluster\", class_type=~\"(log|unset)\"})",
       "legendFormat": "usage max"
      }
     ]
    },
    {
     "title": "Network",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 16 },
     "repeat": "log_processes",
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "fdb_process_network_megabits_received_rate{cluster=\"$cluster\", address=\"$log_process\"}",
       "legendFormat": "received {{address}}"
      },
      {
       "expr": "fdb_process_network_megabits_sent_rate{cluster=\"$cluster\", address=\"$log_process\"}",
       "legendFormat": "sent {{address}}"
      },
      {
       "expr": "max(fdb_process_network_megabits_received_rate{cluster=\"$cluster\", class_type=~\"(log|unset)\"})",
       "legendFormat": "received max"
      },
      {
       "expr": "max(fdb_process_network_megabits_sent_rate{cluster=\"$cluster\", class_type=~\"(log|unset)\"})",
       "legendFormat": "sent max"
      }
     ]
    }
   ]
  },
  {
   "title": "Commit Proxy Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Batching Window Size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "repeat": "commit_proxy_processes",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "fdb_process_commit_proxy_batching_window_size_mean{cluster=\"$cluster\",address=\"$commit_proxy_process\"}",
       "legendFormat": "mean {{address}}"
      },
      {
       "expr": "fdb_process_commit_proxy_batching_window_size_p99{cluster=\"$cluster\",address=\"$commit_proxy_process\"}",
       "legendFormat": "p99 {{address}}"
      },
      {
       "expr": "fdb_process_commit_proxy_batching_window_size_max{cluster=\"$cluster\",address=\"$commit_proxy_process\"}",
       "legendFormat": "max {{address}}"
      }
     ]
    },
    {
     "title": "Commit Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "repeat": "commit_proxy_processes",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "fdb_process_commit_proxy_commit_latency_mean{cluster=\"$cluster\",address=\"$commit_proxy_process\"}",
       "legendFormat": "mean {{address}}"
      },
      {
       "expr": "fdb_process_commit_proxy_commit_latency_p99{cluster=\"$cluster\",address=\"$commit_proxy_process\"}",
       "legendFormat": "p99 {{address}}"
      },
      {
       "expr": "fdb_process_commit_proxy_commit_latency_max{cluster=\"$cluster\",address=\"$commit_proxy_process\"}",
       "legendFormat": "max {{address}}"
      }
     ]
    },
    {
     "title": "CPU $commit_proxy_process",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
     "repeat": "commit_proxy_processes",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "fdb_process_cpu_usage_cores{cluster=\"$cluster\", address=\"$commit_proxy_process\"}",
       "legendFormat": "usage {{address}} {{class_type}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fdb_process_memory_available_bytes{cluster=\"$cluster\", address=\"$commit_proxy_process\"}",
       "legendFormat": "available {{address}}"
      },
      {
       "expr": "fdb_process_memory_used_bytes{cluster=\"$cluster\", address=\"$commit_proxy_process\"}",
       "legendFormat": "used {{address}}"
      },
      {
       "expr": "fdb_process_memory_rss_bytes{cluster=\"$cluster\", address=\"$commit_proxy_process\"}",
       "legendFormat": "rss {{address}}"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 17 },
     "repeat": "commit_proxy_processes",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "fdb_process_disk_usage_ratio{cluster=\"$cluster\", address=\"$commit_proxy_process\"}",
       "legendFormat": "utilization"
      }
     ]
    },
    {
     "title": "Network",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 17 },
     "repeat": "commit_proxy_processes",
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "fdb_process_network_megabits_received_rate{cluster=\"$cluster\", address=\"$commit_proxy_process\"}",
       "legendFormat": "received {{address}}"
      },
      {
       "expr": "fdb_process_network_megabits_sent_rate{cluster=\"$cluster\", address=\"$commit_proxy_process\"}",
       "legendFormat": "sent {{address}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GRV Proxy Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Batch latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "fdb_process_grv_proxy_batch_latency_mean{cluster=\"$cluster\", address=\"$grv_proxy_process\"}",
       "legendFormat": "mean {{address}}"
      },
      {
       "expr": "fdb_process_grv_proxy_batch_latency_p99{cluster=\"$cluster\", address=\"$grv_proxy_process\"}",
       "legendFormat": "p99 {{address}}"
      },
      {
       "expr": "fdb_process_grv_proxy_batch_latency_mean{cluster=\"$cluster\", address=\"$grv_proxy_process\"}",
       "legendFormat": "mean {{address}}"
      }
     ]
    },
    {
     "title": "Default Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "fdb_process_grv_proxy_default_latency_median{cluster=\"$cluster\", address=\"$grv_proxy_process\"}",
       "legendFormat": "mean {{address}}"
      },
      {
       "expr": "fdb_process_grv_proxy_default_latency_p99{cluster=\"$cluster\", address=\"$grv_proxy_process\"}",
       "legendFormat": "p99 {{address}}"
      },
      {
       "expr": "fdb_process_grv_proxy_default_latency_max{cluster=\"$cluster\", address=\"$grv_proxy_process\"}",
       "legendFormat": "max {{address}}"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "fdb_process_cpu_usage_cores{cluster=\"$cluster\",address=\"$grv_proxy_process\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fdb_process_memory_available_bytes{cluster=\"$cluster\", address=\"$grv_proxy_process\"}",
       "legendFormat": "available {{address}}"
      },
      {
       "expr": "fdb_process_memory_used_bytes{cluster=\"$cluster\", address=\"$grv_proxy_process\"}",
       "legendFormat": "used {{address}}"
      },
      {
       "expr": "fdb_process_memory_rss_bytes{cluster=\"$cluster\", address=\"$grv_proxy_process\"}",
       "legendFormat": "rss {{address}}"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "fdb_process_disk_usage_ratio{cluster=\"$cluster\", address=\"$grv_proxy_process\"}",
       "legendFormat": "utilization"
      }
     ]
    },
    {
     "title": "Network",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "fdb_process_network_megabits_received_rate{cluster=\"$cluster\", address=\"$grv_proxy_process\"}",
       "legendFormat": "received {{address}}"
      },
      {
       "expr": "fdb_process_network_megabits_sent_rate{cluster=\"$cluster\", address=\"$grv_proxy_process\"}",
       "legendFormat": "sent {{address}}"
      }
     ]
    }
   ]
  }
 ]
}